questions =  [
    {"id": 0, "question": "The president should have a veto power that can only be overridden by a supermajority.", "effects": {"presidential": 1}},
    {"id": 1, "question": "A separate election is a better way of choosing a president than having them appointed by the legislature.", "effects": {"presidential": 1}},
    {"id": 2, "question": "Having a separate head of government and a head of state is an ideal that can never work in practice.", "effects": {"presidential": 1}},
    {"id": 3, "question": "Motion of no confidence is a bad idea, the state would be better off without it.", "effects": {"presidential": 1}},
    {"id": 4, "question": "The president or someone nominated by the president should form the cabinet.", "effects": {"presidential": 1}},
    {"id": 5, "question": "The government officials cannot be trusted and need to be be easy to remove from power.", "effects": {"presidential": -1}},
    {"id": 6, "question": "Limiting presidential powers is an inherently good idea.", "effects": {"presidential": -1}},
    {"id": 7, "question": "The legislature should have a final say on who will get the governmental positions.", "effects": {"presidential": -1}},
    {"id": 8, "question": "The head of state should not interfere with the government.", "effects": {"presidential": -1}},
    {"id": 9, "question": "The executive branch should answer to the legislature.", "effects": {"presidential": -1}},
    {"id": 10, "question": "Sometimes it is right that the state may redraw the voting districts to prevent fringe groups from getting elected.", "effects": {"popularity": 1}},
    {"id": 11, "question": "The most popular option should be chosen even if a majority disagrees with it.", "effects": {"popularity": 1}},
    {"id": 12, "question": "Core support is necessary for any government to succeed.", "effects": {"popularity": 1}},
    {"id": 13, "question": "The legislature requires a majority party in order to function.", "effects": {"popularity": 1}},
    {"id": 14, "question": "Voting for more than one candidate should invalidate the ballot.", "effects": {"popularity": 1}},
    {"id": 15, "question": "A popular candidate should be preferred over a broadly acceptable one.", "effects": {"popularity": 1}},
    {"id": 16, "question": "The spoiler effect should be made less significant if not completely eliminated.", "effects": {"popularity": -1}},
    {"id": 17, "question": "Without a large approval rate, an election winner is illegitimate.", "effects": {"popularity": -1}},
    {"id": 18, "question": "Ranked-choice voting was not proposed to better represent the people, but to uphold the status-quo while making an illusion of improvement.", "effects": {"popularity": -1}},
    {"id": 19, "question": "A majoritarian electoral college is a bad idea because it gives swing states too much influence over the result.", "effects": {"popularity": -1}},
    {"id": 20, "question": "The composition of opinions in the general population should be reflected in the legislature, even if it leads to unstable coalitions.", "effects": {"pluralism": 1}},
    {"id": 21, "question": "Because the legislature and the government are supposed to uphold the will of the people, the people should be able to demand a snap election.", "effects": {"pluralism": 1}},
    {"id": 22, "question": "A voter should be able to vote for a candidate that is running in a different part of the country.", "effects": {"pluralism": 1}},
    {"id": 23, "question": "Having hundreds of candidates on the ballot is perfectly acceptable.", "effects": {"pluralism": 1}},
    {"id": 24, "question": "Left-wing and right-wing districts are a social construct, not a natural state of affairs.", "effects": {"pluralism": 1}},
    {"id": 25, "question": "A snap election should be called if no coalition is able to form.", "effects": {"pluralism": -1}},
    {"id": 26, "question": "Multi-member constituencies create political instability and should be avoided.", "effects": {"pluralism": -1}},
    {"id": 27, "question": "An electoral threshold should exist for third parties.", "effects": {"pluralism": -1}},
    {"id": 28, "question": "The constitution should never be changed.", "effects": {"pluralism": -1}},
    {"id": 29, "question": "Multi-party politics is bad.", "effects": {"pluralism": -1}}
];
